config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root :to => 'homes#top'
  resources :posts do
    resources :comments, only:[:create, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user  #この行を追記
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  has_one_attached :image
  belongs_to :user
  has_many :comments, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

has_many :posts, dependent: :destroy
has_many :comments, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

  def after_sign_in_path_for(resource)
    posts_path
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    post = Post.find(params[:post_id])
    comment = current_user.comments.new(comment_params)
    comment.post_id = post.id
    comment.save
    redirect_to post_path(post)
  end

  def destroy
    Comment.find_by(id: params[:id], post_id: params[:post_id]).destroy
    redirect_to post_path(params[:post_id])
  end

  private

  def comment_params
    params.require(:comment).permit(:comment)
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.page(params[:page]).per(6)
  end

  def new
    @post = Post.new
  end

  def create
    post = Post.new(post_params)
    post.save
    redirect_to post_path(post.id)
  end

  def show
    @post = Post.find(params[:id])
    @comment = Comment.new  #この行を追記
    @comments = @post.comments.page(params[:page]).per(7).reverse_order
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    post = Post.find(params[:id])
    post.update(post_params)
    redirect_to post_path(post.id)
  end

  def destroy
    post = Post.find(params[:id])
    post.destroy
    redirect_to posts_path
  end

  private
  def post_params
    params.require(:post).permit(:location, :text, :image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/homes/top.html.erb
<div class="cover align-middle">
  <div class="text-center">
    <p class="sub-title">〜あなたのとっておきの”ちゅら海”を共有〜</p>
    <h1 class="title mb-2">OKIUMI</h1>
    <%= link_to new_user_registration_path do %>
     <h2 class="btn btn-primary mr-2">新規登録</h2>
    <% end %>
    <%= link_to new_user_session_path do %>
     <h2 class="btn btn-success ml-2">ログイン</h2>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UmiApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if user_signed_in? %>
    <header>
      <div><%= link_to root_path do %><img src="/assets/okiumi_logo.png" alt="logo" id="logo"><% end %></div>
      <div><%= link_to "トップ", root_path, class: "text-white" %></div>
      <div><%= link_to "投稿する", new_post_path, class: "text-white" %></div>
      <div><%= link_to "投稿一覧", posts_path, class: "text-white" %></div>
      <div><%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "text-white" %></div>
    </header>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/posts/edit.html.erb
<div class="cover-edit">
  <div class="container">
    <div class="row justify-content-center">
      <h1 class="font-weight-normal mt-5 mb-5">旅行投稿編集</h1>
    </div>
    <div class="row justify-content-center">
      <%= form_with model: @post, url:"/posts/#{@post.id}", local:true do |f| %>
      <div class="form-group">
        <label class="form-label">旅行先</label>
        <%= f.text_field :location, class: "form-control" %>
      </div>
      <div class="form-group">
        <label class="form-label">感想</label>
        <%=f.text_area :text, rows: 10, class: "form-control" %>
      </div>
      <div class="form-group">
        <label class="form-label">画像</label><br>
        <%= f.file_field :image %>
      </div>
      <%= f.submit '保存する', class: "btn btn-success" %><br>
      <%= link_to '投稿詳細ページへ', post_path(@post), class: "btn btn-dark mt-3" %>
      <% end %>
    </div>
  </div>
</div>

app/views/posts/index.html.erb
<div class="cover-index">
  <div class="container">
    <div class="row justify-content-center">
      <h1 class="font-weight-normal mt-3">旅行投稿一覧</h1>
    </div>
    <div class="row justify-content-center">
      <% @posts.each do |post| %>
      <div class="one-post">
        <%= link_to post_path(post) do %>
        <p class="caption">ユーザ名</p>
          <%= image_tag post.image, size:"300x200" %>
        <p class="caption mb-0"><%= post.location %></p>
        <p class="caption"><%= "#{post.comments.count} コメント" %></p>
        <% end %>
      </div>
      <% end %>
    </div>
    <%= paginate @posts %>
  </div>
</div>

app/views/posts/new.html.erb
<div class="cover-new">
  <div class="container">
    <div class="row justify-content-center">
      <h1 class="font-weight-normal mt-3">旅行新規投稿</h1>
    </div>
    <div class="row justify-content-center">
      <%= form_with model: @post, url:'/posts', local:true do |f| %>
      <div class="form-group">
        <label class="form-label">旅行先</label>
        <%= f.text_field :location, class: "form-control" %>
      </div>
      <div class="form-group">
        <label class="form-label">感想</label>
        <%=f.text_area :text, rows: 10, class: "form-control" %>
      </div>
      <div class="form-group">
        <label class="form-label">画像</label><br>
        <%= f.file_field :image %>
      </div>
      <%= f.submit '投稿する', class: "btn btn-success" %>
      <% end %>
    </div>
  </div>
</div>

app/views/posts/show.html.erb
<div class="cover-show">
  <div class="container">
    <div class="row justify-content-center">
      <h1 class="font-weight-normal mt-5 mb-5">旅行投稿詳細</h1>
    </div>
    <div class="d-flex">
    <div class="row justify-content-center d-block">
      <p class="caption">ユーザ名</p>
      <% if @post.image.attached? %>
        <%= image_tag @post.image, size:"400x300" %>
      <% end %>
      <p class="caption"><%= @post.location %></p>
      <h2>感想</h2>
      <p id="text"><%= @post.text %></p>
      <%= link_to '編集する', edit_post_path(@post.id), class: "btn btn-info mr-3" %>
      <%= link_to '削除する', post_path(@post.id),method: :delete, "data-confirm"=>"本当に消しますか？", class: "btn btn-danger" %><br>
      <%= link_to '投稿一覧ページへ', posts_path, class: "btn btn-dark mt-3" %>
    </div>

    <div class="comments ml-5 mt-5">
        <%= form_with(model:[@post, @comment], local: true) do |f| %>
        <%= f.text_area :comment, :size=>"60x3",placeholder: "コメントする" %>
        <%= f.submit "送信する", class: "btn btn-success mb-4" %>
        <% end %>

        <p>コメント件数：<%= @comments.count %></p>
          <% @comments.each do |comment| %>
	  <div class="comments-index mb-2">
          <%= comment.user.name %>
          <%= comment.created_at.strftime('%Y/%m/%d') %><br>
          <div class="d-flex">
            <%= comment.comment %>
            <% if comment.user == current_user %>
            <div class="comment-delete">
              <%= link_to "削除", post_comment_path(comment.post, comment), method: :delete, class: "btn-sm btn-danger" %>
            </div>
          </div>
        </div>
        <% end %>
        <% end %>
        <%= paginate @comments %>
      </div>
    </div>
  </div>
</div>